run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - noctx

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - noctx
    - path: _test\.go
      text: shadow
    - path: examples/
      linters:
        - errcheck
        - noctx
  max-issues-per-linter: 50
  max-same-issues: 10
